### PR TITLE
Update to most recent versions of ebean and ninja

### PR DESCRIPTION
**Pull request by xgp**
This updates the versions of ninja and the ebean libs to their most recent versions. We've been running with this in production for a while, so I don't think there are any problems with this. Given the package changes in ebean, maybe we should call it ninja-ebean-ng-ng ;) or at least bump it a major or minor version number.

Thanks!

### CODE REVIEW

**Comment by jfendler** [comment]
@xgp thanks for your PR. Looks good to me, but it'll take a few days until I can push an updated build to the nexus... I've had to restore a backup from my build setup and some of the parts are not yet fully working. I'll merge and update as soon as I can.

**Comment by xgp** [comment]
Thanks for taking a look! No rush here. Let me know if I can help with anything.

**Comment by xgp** [comment]
Updated the PR with the recent ebean versions. Let me know if there is anything I can do to help this get released. Happy new year!

**Comment by xgp** [comment]
FYI, we released a forked version of this at https://github.com/brightback/ebean-guice which takes a slightly different approach to config, but uses the same code as this lib. First version released to Maven central http://central.maven.org/maven2/com/brightback/oss/ebean-guice/0.0.1/
Ebean dependency versions are up to date with current, and we will try to keep them that way.

**Pull request closed without merging**
